// <auto-generated />
using Homework4Umbraco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homework4Umbraco.Migrations
{
    [DbContext(typeof(Homework4UmbracoContext))]
    partial class Homework4UmbracoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClassLibrary.Participant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("SerialNumberID");

                    b.HasKey("ID");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("ClassLibrary.SerialNumber", b =>
                {
                    b.Property<string>("SerialNumberID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SerialNumberID");

                    b.ToTable("SerialNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
